-- AI News Learner MySQL schema
-- Core runtime tables: news, podcasts, podcast_news_mapping, background_info,
-- entity_relation, viewpoint_analysis, users, reading_history, user_vocabulary
-- Auxiliary learning table: vocabulary

-- Create database
CREATE DATABASE IF NOT EXISTS ai_news CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ai_news;

-- Table 1: news (Main table for news data)
CREATE TABLE news (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(500) NOT NULL COMMENT 'Original news title',
    category VARCHAR(50) COMMENT 'News category',
    cover_image VARCHAR(1000) COMMENT 'URL of the news cover image',
    original_url VARCHAR(500) NOT NULL COMMENT 'Source URL for reference',
    source VARCHAR(100) COMMENT 'News source name',
    publish_date DATETIME COMMENT 'Publication time',

    -- Content Fields
    content TEXT NOT NULL COMMENT 'Original English text',
    en_summary TEXT COMMENT 'AI-generated summary paragraph',
    
    -- AI metadata
    difficulty_score INT COMMENT 'Reading difficulty score (1-10)',
    tags JSON COMMENT 'Array of tags generated by AI',
    qa_suggestions JSON COMMENT 'Array of suggested questions',
    
    -- Analytics
    view_count INT DEFAULT 0 COMMENT 'Number of views',
    hot_score FLOAT DEFAULT 0 COMMENT 'Calculated heat score',
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE KEY idx_original_url (original_url(255)),
    INDEX idx_category (category),
    INDEX idx_publish_date (publish_date),
    INDEX idx_hot_score (hot_score)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table 2: podcasts (Multi-news aggregation)
CREATE TABLE podcasts (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    script TEXT COMMENT 'Bilingual podcast script',
    audio_url VARCHAR(1000) COMMENT 'MP3 file URL',
    duration INT COMMENT 'Duration in seconds',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table 3: podcast_news_mapping (Mapping between podcasts and news)
CREATE TABLE podcast_news_mapping (
    id INT PRIMARY KEY AUTO_INCREMENT,
    podcast_id INT NOT NULL,
    news_id INT NOT NULL,
    FOREIGN KEY (podcast_id) REFERENCES podcasts(id) ON DELETE CASCADE,
    FOREIGN KEY (news_id) REFERENCES news(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table 4: vocabulary (Auxiliary word lookup table used by the vocabulary feature)
CREATE TABLE vocabulary (
    id INT PRIMARY KEY AUTO_INCREMENT,
    news_id INT NOT NULL,
    word VARCHAR(100) NOT NULL COMMENT 'Keyword',
    phonetic VARCHAR(50) COMMENT 'International Phonetic Alphabet',
    translation VARCHAR(500) COMMENT 'Chinese translation',
    explanation TEXT COMMENT 'English explanation/definition',
    example_sentence TEXT COMMENT 'Contextual example sentence',

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (news_id) REFERENCES news(id) ON DELETE CASCADE,
    UNIQUE KEY unique_word_per_news (news_id, word),
    INDEX idx_news_id (news_id),
    INDEX idx_word (word)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table 5: background_info (Wiki items)
CREATE TABLE background_info (
    id INT PRIMARY KEY AUTO_INCREMENT,
    news_id INT NOT NULL,
    entity_name VARCHAR(200) NOT NULL,
    entity_type VARCHAR(50),
    description TEXT COMMENT 'Contextual background from AI',
    is_web_searched BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (news_id) REFERENCES news(id) ON DELETE CASCADE,
    INDEX idx_news_id (news_id),
    INDEX idx_entity_name (entity_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table 6: viewpoint_analysis (Sentiment cards)
CREATE TABLE viewpoint_analysis (
    id INT PRIMARY KEY AUTO_INCREMENT,
    news_id INT NOT NULL,
    entity_name VARCHAR(200) NOT NULL,
    viewpoint TEXT COMMENT 'Extracted stance',
    sentiment VARCHAR(100) COMMENT 'Positive/Negative/Neutral',
    FOREIGN KEY (news_id) REFERENCES news(id) ON DELETE CASCADE,
    INDEX idx_news_id (news_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table 7: entity_relation (Knowledge Graph data)
CREATE TABLE entity_relation (
    id INT PRIMARY KEY AUTO_INCREMENT,
    news_id INT NOT NULL,
    subject_entity VARCHAR(200),
    relation VARCHAR(100),
    object_entity VARCHAR(200),
    FOREIGN KEY (news_id) REFERENCES news(id) ON DELETE CASCADE,
    INDEX idx_news_id (news_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- Table 8: user_vocabulary (User's collected vocabulary)
CREATE TABLE user_vocabulary (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id VARCHAR(100) NOT NULL COMMENT 'WeChat user ID',
    word VARCHAR(100) NOT NULL COMMENT 'Collected word',
    news_id INT NOT NULL COMMENT 'Source news article',
    collected_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (news_id) REFERENCES news(id) ON DELETE CASCADE,
    UNIQUE KEY unique_user_word (user_id, word, news_id),
    INDEX idx_user_id (user_id),
    INDEX idx_word (word)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table 9: users (WeChat mini-program users)
CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    openid VARCHAR(100) NOT NULL COMMENT 'WeChat openid',
    nickname VARCHAR(100) COMMENT 'WeChat nickname',
    avatar_url VARCHAR(500) COMMENT 'WeChat avatar URL',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY idx_openid (openid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table 10: reading_history (User news reading history)
CREATE TABLE IF NOT EXISTS reading_history (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id VARCHAR(100) NOT NULL COMMENT 'WeChat openid',
    news_id INT NOT NULL,
    read_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (news_id) REFERENCES news(id) ON DELETE CASCADE,
    UNIQUE KEY unique_user_news (user_id, news_id),
    INDEX idx_user_id (user_id),
    INDEX idx_read_at (read_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
